#------------------------------------
# This is test project workflow
#------------------------------------

# Name for this action
name: My-GitHubActions_Basics
env:                            #specify global variables
  APPLIKATION_NAME: "MyAPP"
  DEPLOY_PACKAGE_NAME : "MyAPP-deploy-ver-${{github.sha}}"    #where github.sha - commit hash number for every commit

    


# Controls when the action will run. 
on:
  push:                       #specify action chich git will be monitor 
    branches:                 #specify branch in which git will be monitor action
      - main
   
# Describe action which git should run
jobs:
  my_testing:                 #First job name
    runs-on: ubuntu-latest    #need specify image docker conteiner, will be run my job on docker 
    
    steps:
    - name: Print Hello Message               #task1 name
      run : echo "Hello World from Testing"   #what task should do
      
    - name: Execute few commands              #task2 name
      run: |                                  #what task should do. I - mens multiple command
        echo "Hello Message1"
        echo "Hello Message2"
        echo "Hello Application name: ${{env.APPLIKATION_NAME}}"

    - name: List current folder
      run: ls -alh
    
    - name: Git clone my repo
      uses: actions/checkout@v1         #it internal script to clone you repo from fit in docker
      
    - name: List current folder after cloning
      run: ls -alh

          
  my_deploys:
    runs-on: ubuntu-latest
    needs: [my_testing]         #run "my_deploys" action after "my_testing" action
    
    steps:
    - name: Print Hello Message
      run : echo "Hello World from Deploy job"
      
    - name: Deployment package
      run: echo "Deploy package name is ${{env.DEPLOY_PACKAGE_NAME}}"
    
    - name: Lets test some packages if they are here 1
      run: aws --version                                 #check installing aws cli on this docker
    
    - name: Lets test some packages if they are here 2
      run: zip                                          #check installing zip tool on this docker
